name: cms-backend-prod

networks:
  traefik-net:
    external: true
    name: ${DOCKER_NETWORK_NAME:-shared-prod-net}

  backend:
    driver: bridge

services:
  app:
    build:
      context: .
      args:
        BUILD_ENV: prod
      target: container-prod
      network: host
    restart: unless-stopped

    environment:
      POETRY_VIRTUALENVS_CREATE: "false"
      POETRY_VIRTUALENVS_IN_PROJECT: "false"
    
    env_file:
      - .env.production

    volumes:
      - /mnt/docker-nfs/cms-media:/media
      - static-data:/app/static

    depends_on:
      redis:
        condition: service_healthy
    command: >
      uwsgi --http 0.0.0.0:8002
      --module root.wsgi:application
      --master
      --processes 4
      --threads 2
      --harakiri 60
      --max-requests 5000
    expose:
      - "8002"

    networks:
      - backend

    healthcheck:
      test: ["CMD-SHELL", "python -c \"import socket; s=socket.socket(); s.settimeout(2); s.connect(('127.0.0.1',8002)); s.close()\""]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 15s

  nginx:
    image: nginx:1.27-alpine
    restart: unless-stopped

    depends_on:
      app:
        condition: service_healthy

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /mnt/docker-nfs/trungtamtrienlam-media:/media:ro
      - static-data:/app/static:ro

    expose:
      - "80"

    labels:
      - traefik.enable=true
      - traefik.docker.network=${DOCKER_NETWORK_NAME:-shared-prod-net}
      - traefik.http.routers.cms-api.rule=Host(`cms-api.hongvan.net`)
      - traefik.http.routers.cms-api.entrypoints=websecure
      - traefik.http.routers.cms-api.tls=true
      - traefik.http.routers.cms-api.service=cms-api
      - traefik.http.services.cms-api.loadbalancer.server.port=80

    networks:
      - backend
      - traefik-net

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

    networks:
      - backend

volumes:
  static-data: