name: cms-backend-dev

networks:
  app-net:
    external: true
    name: app-net

services:
  app:
    build:
      context: .
      args:
        BUILD_ENV: dev
      target: container-dev
      network: host

    environment:
      POETRY_VIRTUALENVS_CREATE: "false"
      POETRY_VIRTUALENVS_IN_PROJECT: "false"

    volumes:
      - ./app/:/app
      - /mnt/docker-nfs/media:/app/media:rw

    depends_on:
      redis:
        condition: service_healthy

    command: ["python", "manage.py", "runserver", "0.0.0.0:8002"]

    networks:
      - app-net

  redis:
    image: redis:7-alpine

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

    networks:
      - app-net