# Generated by Django 4.2.3 on 2023-08-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.IntegerField(choices=[(0, 'Collector'), (1, 'Artist'), (2, 'Gallery owner'), (3, 'Service provider')], default=1),
        ),
    ]
