# Generated by Django 4.2.3 on 2023-08-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'Collector'), (1, 'Artist'), (2, 'Gallery owner'), (3, 'Service provider')], default=1),
        ),
    ]
