# Generated by Django 4.2.3 on 2023-08-25 03:33

import common.abstract_models.image_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userprofile_role_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background',
            field=common.abstract_models.image_field.CustomImageField(blank=True, upload_to=''),
        ),
    ]
