# Generated by Django 4.2.3 on 2023-10-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_email_userprofile_live_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about_artist',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
