# Generated by Django 4.2.3 on 2023-10-16 09:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_usersoloexhibition_userpublication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='membership',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(default=dict), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='place_of_birth',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='training_background',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(default=dict), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='year_of_birth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
