# Generated by Django 4.2.3 on 2023-10-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userprofile_membership_userprofile_place_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='year_of_birth',
            field=models.CharField(blank=True, null=True),
        ),
    ]
