# Generated by Django 4.2.3 on 2023-12-08 04:14

import common.abstract_models.image_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_userprofile_year_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='signature',
            field=common.abstract_models.image_field.CustomImageField(blank=True, null=True, upload_to=''),
        ),
    ]
