# Generated by Django 4.2.3 on 2024-01-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_userprofile_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(blank=True, choices=[(1, 'Artist'), (2, 'Gallery owner'), (3, 'Service provider'), (4, 'Collector')], null=True),
        ),
    ]
