# Generated by Django 4.2.3 on 2024-02-23 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about_artist',
            field=models.TextField(blank=True, max_length=6000, null=True),
        ),
    ]
