# Generated by Django 4.2.3 on 2024-03-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_userinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_activated',
            field=models.BooleanField(default=False),
        ),
    ]
