# Generated by Django 4.2.3 on 2024-05-14 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_has_activated'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVisibleSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public_profile', models.BooleanField(default=True)),
                ('is_public_exhibition', models.BooleanField(default=True)),
                ('is_public_artwork', models.BooleanField(default=True)),
                ('is_public_follower', models.BooleanField(default=True)),
                ('is_public_social_media', models.BooleanField(default=True)),
                ('is_public_personal_info', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visible_setting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
