# Generated by Django 4.2.3 on 2024-05-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_uservisiblesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='legal_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='place_of_birth',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='year_of_birth',
            field=models.CharField(blank=True, null=True),
        ),
    ]
