# Generated by Django 4.2.3 on 2024-07-12 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_user_legal_name_user_place_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('saved_user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_users',
                                   to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
