# Generated by Django 4.2.3 on 2024-07-12 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_saveduser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saveduser',
            old_name='saved_at',
            new_name='created_at',
        ),
    ]