# Generated by Django 4.2.3 on 2024-07-24 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_rename_saved_at_saveduser_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveduser',
            name='contact_info_saved_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='saveduser',
            name='name_saved_user',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='saveduser',
            name='saved_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
