# Generated by Django 4.2.3 on 2024-10-21 04:24

from django.db import migrations

from core.accounts.ultils.migrations.migrate_update_uuid_user import update_field_uuid_user


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_user_uuid'),
    ]

    def migrate_update_field_uuid_user(apps, schema_editor):
        User = apps.get_model('accounts', 'User')
        update_field_uuid_user(User)

    operations = [
        migrations.RunPython(migrate_update_field_uuid_user,
                             migrations.RunPython.noop)
    ]
