# Generated by Django 4.2.3 on 2024-11-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveduser',
            name='year_of_birth',
            field=models.CharField(blank=True, null=True),
        ),
    ]
