# Generated by Django 4.2.17 on 2024-12-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_saveduser_year_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraward',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='usergroupexhibition',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='about_artist',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='certification',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='introduction',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userpublication',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='usersoloexhibition',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
