# Generated by Django 4.2.17 on 2025-02-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_useraward_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='introduction',
            field=models.TextField(blank=True, max_length=6000, null=True),
        ),
    ]
