# Generated by Django 4.2.17 on 2025-02-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_userprofile_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroupexhibition',
            name='to_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usersoloexhibition',
            name='to_year',
            field=models.IntegerField(null=True),
        ),
    ]
