# Generated by Django 4.2.17 on 2025-02-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_usergroupexhibition_to_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroupexhibition',
            name='to_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usergroupexhibition',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersoloexhibition',
            name='to_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersoloexhibition',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
