# Generated by Django 4.2.17 on 2025-02-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_usergroupexhibition_to_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraward',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpublication',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
