# Generated by Django 4.2.17 on 2025-03-07 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_code', models.CharField(blank=True, choices=[('RECEIVE_CERTIFICATE_REQUEST', 'RECEIVE_CERTIFICATE_REQUEST')], max_length=100, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('title_vi', models.CharField(blank=True, max_length=255, null=True)),
                ('content_en', models.CharField(blank=True, max_length=355, null=True)),
                ('content_vi', models.CharField(blank=True, max_length=355, null=True)),
                ('redirect', models.CharField(max_length=355)),
            ],
        ),
        migrations.RemoveField(
            model_name='notification',
            name='content',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
        migrations.AddField(
            model_name='notification',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='accounts.notificationtemplate'),
        ),
    ]
