# Generated by Django 4.2.17 on 2025-03-07 03:24

from django.db import migrations

from core.accounts.models.notification_template import NOTIFICATIONS_CONTENT_CODE


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_notificationtemplate_remove_notification_content_and_more'),
    ]

    def migrate_create_notification_template(apps, schema_editor):
        NotificationTemplate = apps.get_model('accounts', 'NotificationTemplate')
        NotificationTemplate.objects.create(
            content_code=NOTIFICATIONS_CONTENT_CODE.RECEIVE_CERTIFICATE_REQUEST,
            title_en='Gladius Art',
            title_vi='Gladius Art',
            content_en='{request_user_name} requested a certificate of the artwork {artwork_title}.',
            content_vi='{request_user_name} đã yêu cầu tạo chứng nhận cho tác phẩm {artwork_title}.',
            redirect='/review-certificate-request/{certificate_request_id}'
        )

    operations = [
        migrations.RunPython(migrate_create_notification_template, migrations.RunPython.noop),
    ]
