# Generated by Django 4.2.17 on 2025-07-17 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_usercollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveduser',
            name='connected_artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connected_artists', to=settings.AUTH_USER_MODEL),
        ),
    ]
