# Generated by Django 4.2.17 on 2025-09-18 02:31

from django.db import migrations

from core.accounts.ultils.migrations.migrate_update_is_frist_login import update_field_is_first_login


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_user_is_first_login'),
    ]

    def migrate_update_is_first_login(apps, schema_editor):
        User = apps.get_model('accounts', 'User')
        update_field_is_first_login(User)

    operations = [
        migrations.RunPython(migrate_update_is_first_login,
                             migrations.RunPython.noop)
    ]
