# Generated by Django 4.2.17 on 2025-11-11 09:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_auto_20250918_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uuid_last_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, unique=True),
        ),
    ]
