# Generated by Django 4.2.17 on 2025-11-17 07:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_user_uuid_last_updated_at_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, error_messages={'unique': 'Gladius ID already in use.'}, unique=True),
        ),
    ]
