# Generated by Django 4.2.17 on 2025-11-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='content_code',
            field=models.CharField(blank=True, choices=[('RECEIVE_CERTIFICATE_REQUEST', 'RECEIVE_CERTIFICATE_REQUEST'), ('TRANSFER_OWNERSHIP_RECIPIENT', 'TRANSFER_OWNERSHIP_RECIPIENT')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='content_code',
            field=models.CharField(blank=True, choices=[('RECEIVE_CERTIFICATE_REQUEST', 'RECEIVE_CERTIFICATE_REQUEST'), ('TRANSFER_OWNERSHIP_RECIPIENT', 'TRANSFER_OWNERSHIP_RECIPIENT')], max_length=100, null=True),
        ),
    ]
