# Generated by Django 4.2.17 on 2026-01-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_alter_notification_content_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='content_code',
            field=models.CharField(blank=True, choices=[('RECEIVE_CERTIFICATE_REQUEST', 'RECEIVE_CERTIFICATE_REQUEST'), ('TRANSFER_OWNERSHIP_RECIPIENT', 'TRANSFER_OWNERSHIP_RECIPIENT'), ('SHARE_LINK_INVITATION', 'SHARE_LINK_INVITATION'), ('SHARE_LINK_INVITATION_NO_TITLE', 'SHARE_LINK_INVITATION_NO_TITLE'), ('APPROVE_CERTIFICATE_REQUEST', 'APPROVE_CERTIFICATE_REQUEST')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='content_code',
            field=models.CharField(blank=True, choices=[('RECEIVE_CERTIFICATE_REQUEST', 'RECEIVE_CERTIFICATE_REQUEST'), ('TRANSFER_OWNERSHIP_RECIPIENT', 'TRANSFER_OWNERSHIP_RECIPIENT'), ('SHARE_LINK_INVITATION', 'SHARE_LINK_INVITATION'), ('SHARE_LINK_INVITATION_NO_TITLE', 'SHARE_LINK_INVITATION_NO_TITLE'), ('APPROVE_CERTIFICATE_REQUEST', 'APPROVE_CERTIFICATE_REQUEST')], max_length=100, null=True),
        ),
    ]
