# Generated by Django 4.2.17 on 2026-04-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0003_payment_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoboothDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, help_text='Mã cố định do app tạo lần đầu (UUID), hiển thị trong Admin để đối chiếu khi cài máy.', max_length=128, unique=True)),
                ('name', models.CharField(help_text='Tên hiển thị / vị trí booth — phải khớp VITE_PHOTOBOOTH_DEVICE_NAME trên máy.', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Thiết bị photobooth',
                'verbose_name_plural': 'Thiết bị photobooth',
                'db_table': 'photobooth_device',
            },
        ),
    ]
