# Generated by Django 4.2.17 on 2026-04-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0004_photobooth_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoboothdevice',
            name='device_id',
            field=models.CharField(db_index=True, help_text='Duy nhất toàn hệ thống — một device_id = một máy (một bản ghi).', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='photoboothdevice',
            name='name',
            field=models.CharField(help_text='Tên hiển thị; client có thể gửi khi đăng ký hoặc để server dùng tên mặc định.', max_length=200),
        ),
    ]
