# Generated by Django 4.2.17 on 2026-04-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0005_alter_photoboothdevice_device_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoboothdevice',
            name='address',
            field=models.CharField(blank=True, default='', help_text='Tùy chọn — nhập tay trong Admin.', max_length=500, verbose_name='Địa chỉ'),
        ),
        migrations.AddField(
            model_name='photoboothdevice',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Ghi chú / mô tả booth — không bắt buộc.', verbose_name='Thông tin thêm'),
        ),
    ]
