# Generated by Django 4.2.17 on 2026-04-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0006_photobooth_device_address_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoboothBackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Mã cố định cho API/FE, ví dụ: bg-1, museum-wall', max_length=64, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('image', models.ImageField(blank=True, help_text='Ảnh nền / preview (tùy chọn).', null=True, upload_to='photobooth/backgrounds/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Background',
                'verbose_name_plural': 'Backgrounds',
                'db_table': 'photobooth_background',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PhotoboothFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Mã cố định cho API/FE, ví dụ: hong-hao, vintage', max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, help_text='Ảnh thumbnail / preview filter (tùy chọn).', null=True, upload_to='photobooth/filters/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Filter',
                'verbose_name_plural': 'Filters',
                'db_table': 'photobooth_filter',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='photoboothdevice',
            name='backgrounds',
            field=models.ManyToManyField(blank=True, related_name='devices', to='photobooth.photoboothbackground', verbose_name='Backgrounds'),
        ),
        migrations.AddField(
            model_name='photoboothdevice',
            name='filters',
            field=models.ManyToManyField(blank=True, related_name='devices', to='photobooth.photoboothfilter', verbose_name='Filters'),
        ),
    ]
