# Generated by Django 4.2.17 on 2026-04-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0009_photobooth_decor_frame'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='payos_order_code',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='payos_payment_link_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
