# Generated by Django 4.2.17 on 2026-04-03 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0010_paymentorder_payos_order_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentorder',
            options={'ordering': ['-id'], 'verbose_name': 'Đơn thanh toán', 'verbose_name_plural': 'Đơn thanh toán'},
        ),
    ]
