# Generated by Django 4.2.17 on 2026-04-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0013_paymentorder_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturepackage',
            name='description_line_1_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description line 1 (EN)'),
        ),
        migrations.AddField(
            model_name='capturepackage',
            name='description_line_2_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description line 2 (EN)'),
        ),
        migrations.AddField(
            model_name='capturepackage',
            name='name_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='Name (EN)'),
        ),
        migrations.AlterField(
            model_name='imagephotobooth',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
