# Generated by Django 4.2.17 on 2026-04-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0015_photoboothdevice_printer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoboothSticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Mã cố định cho API/FE, ví dụ: stk-happy, stk-cat', max_length=64, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('image', models.ImageField(blank=True, help_text='Ảnh sticker (PNG trong suốt).', null=True, upload_to='photobooth/stickers/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sticker',
                'verbose_name_plural': 'Stickers',
                'db_table': 'photobooth_sticker',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='photoboothdevice',
            name='stickers',
            field=models.ManyToManyField(blank=True, related_name='devices', to='photobooth.photoboothsticker', verbose_name='Stickers'),
        ),
    ]
