# Generated by Django 5.0.4 on 2026-04-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0016_photoboothsticker_photoboothdevice_stickers'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoboothdecorframe',
            name='type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('grid4', '4 lần chụp (lưới)'),
                    ('strip4', '4 lần chụp (dọc)'),
                    ('grid6', '6 lần chụp'),
                ],
                default=None,
                help_text='Loại layout: grid4, strip4, grid6. Để trống = hiển thị cho tất cả.',
                max_length=16,
                null=True,
            ),
        ),
    ]
