# Generated by Django 4.2.17 on 2026-04-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0017_photoboothdecorframe_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoboothdecorframe',
            name='type',
            field=models.CharField(blank=True, choices=[('grid4', '4 lần chụp (lưới)'), ('strip4', '4 lần chụp (dọc)'), ('grid6', '6 lần chụp'), ('singleLarge', '1 lần chụp - Ảnh lớn'), ('idphoto', '1 lần chụp - Ảnh thẻ 4×6')], default=None, help_text='Loại layout: grid4, strip4, grid6, singleLarge, idphoto. Để trống = hiển thị cho tất cả.', max_length=16, null=True),
        ),
    ]
