# Generated by Django 4.2.17 on 2026-04-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0018_alter_photoboothdecorframe_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='payment_method',
            field=models.CharField(choices=[('vietqr', 'VietQR (payOS)'), ('vnpay', 'VNPAY'), ('paypal', 'PayPal')], db_index=True, default='vietqr', max_length=16, verbose_name='Phương thức thanh toán'),
        ),
    ]
