"""
Django settings for root project.
Generated by 'django-admin startproject' using Django 2.2.5.
For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import environ
import logging
import os
import sentry_sdk
import sys
from celery.schedules import crontab
from corsheaders.defaults import default_headers
from django.utils.translation import gettext_lazy as _
from sentry_sdk.integrations.celery import CeleryIntegration
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.logging import LoggingIntegration
from sentry_sdk.integrations.redis import RedisIntegration
from sentry_sdk.integrations.tornado import TornadoIntegration

# https://github.com/joke2k/django-environ
env = environ.Env(
    DEBUG=(bool, False),
    LOGGING_LEVEL=(str, 'INFO'),
    SECRET_KEY=(str, '33d#&1-)0cus@w(p@h^)&*xw)r4sr+hzo2*)l$zyvc+jxl00#3'),
    EMAIL_BACKEND=(str, 'django.core.mail.backends.smtp.EmailBackend'),
    CELERY_EMAIL_BACKEND=(str, 'sendgrid_backend.SendgridBackend'),
    CELERY_TASK_ALWAYS_EAGER=(bool, False),
    CELERY_WORKER_CONCURRENCY=(int, 1),
    CELERY_WORKER_MAX_TASKS_PER_CHILD=(int, 1000),
    CELERY_RESULT_BACKEND=(str, ''),
    EMAIL_HOST=(str, 'smtp.gmail.com'),
    EMAIL_HOST_USER=(str, 'gladiusartproject@gmail.com'),
    EMAIL_HOST_PASSWORD=(str, 'jgagxxqymgmgyxlt'),
    EMAIL_PORT=(int, 587),
    EMAIL_USE_TLS=(bool, True),
    EMAIL_SENDER=(str, ''),
    EMAIL_SERVICE=(str, 'device.service@eoh.io'),
    ERA_HOME_PAGE=(str, 'https://app.e-ra.io/'),
    ERA_RETURN_URL=(str, 'https://app.e-ra.io/processing'),
    SENDGRID_API_KEY=(str, ''),
    SENDGRID_SANDBOX_MODE_IN_DEBUG=(bool, False),
    DEFAULT_FILE_STORAGE=(str, 'django.core.files.storage.FileSystemStorage'),
    MEDIA_URL=(str, '/media/'),
    AWS_S3_CUSTOM_DOMAIN=(str, ''),
    AWS_STORAGE_BUCKET_NAME=(str, 'aws'),
    AWS_BUCKET_PATH_CODEGEN=(str, 'tmp_codegen'),
    CORS_ORIGIN_ALLOW_ALL=(bool, False),
    SITE_ID=(int, 1),
    ROOT_URLCONF=(str, 'root.urls'),
    DB_CONN_MAX_AGE=(int, 60),
    ALLOW_HEADERS_LIST=(str, ''),
    CSRF_TRUSTED_ORIGINS=(str, ''),

    THROTTLE_RATES_ANON=(str, '3000/hour'),
    THROTTLE_RATES_USER=(str, '3000/hour'),
    THROTTLE_RATES_USER_SEND_OTP=(str, '1/minute'),
    THROTTLE_RATES_USER_REGISTER=(str, '100/minute'),
    THROTTLE_RATES_USER_VERIFY_OTP=(str, '100/day'),
    PHONE_VERIFICATION_TIMEOUT=(int, 60),
    ACCOUNT_DEFAULT_HTTP_PROTOCOL=(str, 'http'),

    GOOGLE_MAP_API_KEY=(str, ''),
    LOGIN_REDIRECT_URL=(str, '/'),

    SMS_API_KEY=(str, ''),
    SMS_SECRET_KEY=(str, ''),
    SMS_OPT_TIMEOUT=(int, 60),  # seconds
    HASH_CODE_AUTO_FILL_SMS=(str, '%!@GV$'),

    ONESIGNAL_APP_KEY=(str, 'os_v2_app_v4b2chchsvetbbhh6b76d6rlat65cj7vlcjem45sczsg3'
                            'bq3b5eutbes2bweukdoy4itgboijzhrzvw7ovlagsprvwiby7kqg2cgcki'),
    ONESIGNAL_APP_ID=(str, 'af03a11c-4795-4930-84e7-f07fe1fa2b04'),

    SENTRY_IGNORE_ERRORS=(str, ''),
    SENTRY_DSN=(str, 'SENTRY_DSN'),

    PRIMARY_SITE_URL=(str, 'https://staging-app.gladiusart.com'),
    SENDBIRD_API_URL=(str, 'https://api-FA94005A-F10F-45F2-A5DB-69DCAB9D54DD.sendbird.com/v3'),
    API_TOKEN_SENDBIRD=(str, '8870ec2679dd41234648fc8caf09e51664c7edc5'),
    # SENDBIRD_API_URL=(str, 'https://api-8343C0C0-0E9B-4428-8C96-6C9295E527F8.sendbird.com/v3'),
    # API_TOKEN_SENDBIRD=(str, '10b508f079bdb22a6a5e7da2eb18e3badedfaedb'),

    VNPAY_TMN_CODE=(str, ''),
    VNPAY_HASH_SECRET=(str, ''),
    VNPAY_PAYMENT_URL=(str, 'https://sandbox.vnpayment.vn/paymentv2/vpcpay.html'),
    VNPAY_RETURN_URL=(str, ''),
    # Để trống = khách chọn cổng trên trang VNPAY. VNPAYQR chỉ bật khi merchant sandbox đã bật kênh QR; nếu không dễ gặp code 70 (sai chữ ký) tùy cấu hình cổng.
    VNPAY_DEFAULT_BANK_CODE=(str, ''),
    # payOS — payment gateway thay thế VNPAY (https://payos.vn)
    PAYOS_CLIENT_ID=(str, ''),
    PAYOS_API_KEY=(str, ''),
    PAYOS_CHECKSUM_KEY=(str, ''),
    PAYOS_RETURN_URL=(str, ''),
    PAYOS_CANCEL_URL=(str, ''),
    # PayPal — live REST API (https://developer.paypal.com)
    PAYPAL_CLIENT_ID=(str, ''),
    PAYPAL_SECRET_KEY=(str, ''),
    PAYPAL_MODE=(str, 'live'),  # 'sandbox' or 'live'
    # Tên thiết bị hiển thị khi client không gửi `name` (POST /api/photobooth/devices/register/).
    PHOTOBOOTH_DEVICE_DEFAULT_NAME=(str, 'Photobooth'),
)

IS_TEST = 'test' in sys.argv or 'pytest' in sys.argv[0] or os.getenv('IS_TEST')
if IS_TEST:
    os.environ.setdefault('IS_TEST', '1')
# Load .env.local for runserver and any manage.py command (migrate, createsuperuser, shell, …)
IS_LOCAL = (
    'runserver' in sys.argv
    or 'runserver_plus' in sys.argv
    or (sys.argv and os.path.basename(sys.argv[0]) == 'manage.py')
)

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
root = environ.Path(__file__) - 2  # 2 level above
# BASE_DIR = root()
BASE_DIR = root()

if IS_TEST:
    environ.Env.read_env(os.path.join(BASE_DIR, '.env.test'))

if IS_LOCAL:
    environ.Env.read_env(os.path.join(BASE_DIR, '.env.local'))

if not IS_TEST:
    env_files = ['.env', '/config/.env']
    for env_file in env_files:
        if os.path.isfile(env_file):
            environ.Env.read_env(env_file)

LOGOUT_REDIRECT_URL = '/'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')
IS_PRODUCTION = False


def split_csv(value):
    return [item.strip() for item in value.split(',') if item.strip()]

ALLOWED_HOSTS_CONFIG = env('ALLOWED_HOSTS')  # type: str
if ALLOWED_HOSTS_CONFIG:
    ALLOWED_HOSTS = split_csv(ALLOWED_HOSTS_CONFIG)
else:
    ALLOWED_HOSTS = []

# Trust X-Forwarded-Proto từ nginx reverse proxy → request.build_absolute_uri() trả https://
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

CSRF_TRUSTED_ORIGINS = split_csv(env('CSRF_TRUSTED_ORIGINS'))
if IS_LOCAL or DEBUG:
    CSRF_TRUSTED_ORIGINS.extend([
        'https://*.ngrok-free.dev',
        'https://*.ngrok.app',
        'https://*.ngrok.io',
    ])
CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(CSRF_TRUSTED_ORIGINS))

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django.contrib.postgres',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'corsheaders',
    'djcelery_email',
    'django_extensions',
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
    'drf_yasg',
    'dj_rest_auth',
    'dj_rest_auth.registration',
    'django_celery_beat',
    'green_migration',
    'qr_code',

    # 2FA
    'django_otp',
    'django_otp.plugins.otp_static',
    'django_otp.plugins.otp_totp',
    'two_factor',
    'two_factor.plugins.phonenumber',
    'core.accounts',
    'core.accounts.custom_providers.custom_google',

    'common',
    'core.photobooth',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # https://github.com/ottoyiu/django-cors-headers
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'core.accounts.middlewares.CsrfViewMiddleware',  # custom csrf
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # https://django-two-factor-auth.readthedocs.io/en/stable/installation.html
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]

if not IS_TEST:  # setup debug toolbar
    INSTALLED_APPS += ['debug_toolbar']
    index = MIDDLEWARE.index('corsheaders.middleware.CorsMiddleware')
    DEBUG_MIDDLEWARE = [
        'debug_toolbar.middleware.DebugToolbarMiddleware',
        'common.middleware.wrap_json_for_debug_toolbar',
    ]
    MIDDLEWARE = MIDDLEWARE[:index] + DEBUG_MIDDLEWARE + MIDDLEWARE[index:]
    # https://django-debug-toolbar.readthedocs.io/en/latest/configuration.html#debug-toolbar-config
    DEBUG_TOOLBAR_CONFIG = {
        'SHOW_TOOLBAR_CALLBACK': 'common.utils.debug_toolbar.show_toolbar',
    }
    DEBUG_TOOLBAR_PANELS = [
        'debug_toolbar.panels.history.HistoryPanel',
        'debug_toolbar.panels.versions.VersionsPanel',
        'debug_toolbar.panels.timer.TimerPanel',
        'debug_toolbar.panels.settings.SettingsPanel',
        'debug_toolbar.panels.headers.HeadersPanel',
        'debug_toolbar.panels.request.RequestPanel',
        'debug_toolbar.panels.sql.SQLPanel',
        'debug_toolbar.panels.staticfiles.StaticFilesPanel',
        'debug_toolbar.panels.templates.TemplatesPanel',
        # 'debug_toolbar.panels.cache.CachePanel',  # debug toolbar version 4.0 has issue with cache panel
        'debug_toolbar.panels.signals.SignalsPanel',
        'debug_toolbar.panels.redirects.RedirectsPanel',
        'debug_toolbar.panels.profiling.ProfilingPanel',
    ]

ROOT_URLCONF = env('ROOT_URLCONF')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'root.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
DATABASES = {
    'default': env.db(),
}
# https://docs.djangoproject.com/en/3.1/ref/settings/#conn-max-age
DB_CONN_MAX_AGE = env('DB_CONN_MAX_AGE')

DATABASES['default']['CONN_MAX_AGE'] = DB_CONN_MAX_AGE

# https://docs.djangoproject.com/en/2.0/ref/settings/#caches
CACHES = {
    'default': {
        **env.cache(),
        'BACKEND': 'django_redis.cache.RedisCache',
    },
}

# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-user-model
AUTH_USER_MODEL = 'accounts.User'
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.BCryptPasswordHasher',
]

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-US'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_ROOT = root('static')
STATIC_URL = '/static/'
STATICFILES_DIRS = (
    root('staticfiles'),
)
MEDIA_ROOT = root('media')
MEDIA_URL = env('MEDIA_URL')

# https://github.com/pmclanahan/django-celery-email
EMAIL_BACKEND = env('EMAIL_BACKEND')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL')
vars().update(env.email(backend=EMAIL_BACKEND))

# https://github.com/sklarsa/django-sendgrid-v5
SENDGRID_API_KEY = env('SENDGRID_API_KEY')
SENDGRID_SANDBOX_MODE_IN_DEBUG = env('SENDGRID_SANDBOX_MODE_IN_DEBUG')
CELERY_EMAIL_BACKEND = env('CELERY_EMAIL_BACKEND')
EMAIL_SENDER = env('EMAIL_SENDER')
EMAIL_SERVICE = env('EMAIL_SERVICE')
CELERY_EMAIL_TASK_CONFIG = {
    'queue': 'email',
}

# https://docs.sentry.io/platforms/python/django/?_ga=2.23805178.1591677347.1539400796-2037531365.1522374040
SentryErrorLogging = LoggingIntegration(
    level=logging.ERROR,
    event_level=logging.ERROR,
)

if env('SENTRY_DSN'):
    IGNORE_ERRORS = []
    if env('SENTRY_IGNORE_ERRORS'):
        IGNORE_ERRORS = env('SENTRY_IGNORE_ERRORS').split(',')  # type: list
        IGNORE_ERRORS = list(filter(lambda x: (x != ''), IGNORE_ERRORS))


    def before_send(event, hint):
        if 'exc_info' in hint:
            exc_type, exc_value, tb = hint['exc_info']
            if IGNORE_ERRORS and exc_value.args[0].startswith(tuple(IGNORE_ERRORS)):
                return None
        elif 'log_record' in hint:
            if IGNORE_ERRORS and hint['log_record'].msg.startswith(tuple(IGNORE_ERRORS)):
                return None
        return event


    sentry_sdk.init(
        dsn=env('SENTRY_DSN'),
        before_send=before_send,
        environment=env('ENVIRONMENT'),
        integrations=[
            DjangoIntegration(),
            CeleryIntegration(),
            RedisIntegration(),
            TornadoIntegration(),
            SentryErrorLogging,
        ],
    )

# https://github.com/ottoyiu/django-cors-headers
CORS_ORIGIN_WHITELIST_STR = env('CORS_ORIGIN_WHITELIST')  # type: str
CORS_ORIGIN_WHITELIST = split_csv(CORS_ORIGIN_WHITELIST_STR)
CORS_ORIGIN_ALLOW_ALL = env('CORS_ORIGIN_ALLOW_ALL')

CORS_ALLOW_HEADERS = list(default_headers)
ALLOW_HEADERS_LIST = env('ALLOW_HEADERS_LIST')
if ALLOW_HEADERS_LIST:
    CORS_ALLOW_HEADERS += ALLOW_HEADERS_LIST.split(',')

# VNPAY PAY — điền VNPAY_TMN_CODE, VNPAY_HASH_SECRET, VNPAY_RETURN_URL trong .env.local (không commit secret).
VNPAY_TMN_CODE = env('VNPAY_TMN_CODE')
VNPAY_HASH_SECRET = env('VNPAY_HASH_SECRET')
VNPAY_PAYMENT_URL = env('VNPAY_PAYMENT_URL')
VNPAY_RETURN_URL = env('VNPAY_RETURN_URL')
VNPAY_DEFAULT_BANK_CODE = env('VNPAY_DEFAULT_BANK_CODE')

# payOS — payment gateway (https://payos.vn)
PAYOS_CLIENT_ID = env('PAYOS_CLIENT_ID')
PAYOS_API_KEY = env('PAYOS_API_KEY')
PAYOS_CHECKSUM_KEY = env('PAYOS_CHECKSUM_KEY')
PAYOS_RETURN_URL = env('PAYOS_RETURN_URL')
PAYOS_CANCEL_URL = env('PAYOS_CANCEL_URL')

# PayPal — live REST API credentials
PAYPAL_CLIENT_ID = env('PAYPAL_CLIENT_ID')
PAYPAL_SECRET_KEY = env('PAYPAL_SECRET_KEY')
PAYPAL_MODE = env('PAYPAL_MODE')

PHOTOBOOTH_DEVICE_DEFAULT_NAME = env('PHOTOBOOTH_DEVICE_DEFAULT_NAME')

# http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html
# https://docs.celeryq.dev/en/3.1/configuration.html
CELERY_BROKER_URL = env('CELERY_BROKER_URL')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND')
CELERY_TASK_ALWAYS_EAGER = env('CELERY_TASK_ALWAYS_EAGER') or IS_TEST
CELERY_TASK_EAGER_PROPAGATES = CELERY_TASK_ALWAYS_EAGER
CELERY_WORKER_MAX_TASKS_PER_CHILD = env('CELERY_WORKER_MAX_TASKS_PER_CHILD')
CELERY_BEAT_SCHEDULE = {}  # to use this setting, you need to enable beat.temp.yaml deployment, by rename to beat.yaml
CELERY_WORKER_CONCURRENCY = env('CELERY_WORKER_CONCURRENCY')

INTERNAL_IPS = env('INTERNAL_IPS').split(',')  # type: list

THROTTLE_RATES_ANON = env('THROTTLE_RATES_ANON')
THROTTLE_RATES_USER = env('THROTTLE_RATES_USER')
THROTTLE_RATES_USER_VERIFY_OTP = env('THROTTLE_RATES_USER_VERIFY_OTP')
THROTTLE_RATES_USER_SEND_OTP = env('THROTTLE_RATES_USER_SEND_OTP')
THROTTLE_RATES_USER_REGISTER = env('THROTTLE_RATES_USER_REGISTER')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': THROTTLE_RATES_ANON,
        'user': THROTTLE_RATES_USER,
        'user_send_otp': THROTTLE_RATES_USER_SEND_OTP,
        'user_verify_otp': THROTTLE_RATES_USER_VERIFY_OTP,
        'dj_rest_auth': '1/s',
    },
    'EXCEPTION_HANDLER': 'common.api_exception_handler.custom_exception_handler',
}

OAUTH2_PROVIDER = {
    'PKCE_REQUIRED': False,
    'OAUTH2_VALIDATOR_CLASS': 'core.oauth2.oauth2_validators.custom_oauth2_validator.CustomOAuth2Validator',
}
OAUTH2_PROVIDER_APPLICATION_MODEL = 'accounts.Application'

AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME')
FILE_STORAGE_BACKEND = env('DEFAULT_FILE_STORAGE')
if IS_TEST:
    FILE_STORAGE_BACKEND = 'django.core.files.storage.FileSystemStorage'
STORAGES = {
    'default': {
        'BACKEND': FILE_STORAGE_BACKEND,
    },
    'staticfiles': {
        'BACKEND': FILE_STORAGE_BACKEND,
    },
}

AWS_DEFAULT_ACL = 'public-read'
AWS_S3_CUSTOM_DOMAIN = env('AWS_S3_CUSTOM_DOMAIN')
AWS_S3_FILE_OVERWRITE = False
AWS_BUCKET_PATH_CODEGEN = env('AWS_BUCKET_PATH_CODEGEN')

LOCATION_FIELD_PATH = STATIC_URL + 'location_field'
LOCATION_FIELD = {
    'map.provider': 'google',
    'map.zoom': 13,

    'search.provider': 'google',
    'search.suffix': '',

    # Google
    'provider.google.api': '//maps.google.com/maps/api/js?sensor=false',
    'provider.google.api_key': env('GOOGLE_MAP_API_KEY'),
    'provider.google.api_libraries': '',
    'provider.google.map.type': 'ROADMAP',

    # Mapbox
    'provider.mapbox.access_token': '',
    'provider.mapbox.max_zoom': 18,
    'provider.mapbox.id': 'mapbox.streets',

    # OpenStreetMap
    'provider.openstreetmap.max_zoom': 18,

    # misc
    'resources.root_path': LOCATION_FIELD_PATH,
    'resources.media': {
        'js': (
            LOCATION_FIELD_PATH + '/js/form.js',
        ),
    },
}

# https://django-allauth.readthedocs.io/en/latest/configuration.html
SOCIALACCOUNT_ADAPTER = 'core.accounts.adapter.custom_social_account_adapter.CustomSocialAccountAdapter'
SOCIALACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_QUERY_EMAIL = True
ACCOUNT_DEFAULT_HTTP_PROTOCOL = env('ACCOUNT_DEFAULT_HTTP_PROTOCOL')
ACCOUNT_UNIQUE_EMAIL = False

SWAGGER_SETTINGS = {
    'DEFAULT_PAGINATOR_INSPECTORS': [
        'drf_yasg.inspectors.DjangoRestResponsePagination',
        'drf_yasg.inspectors.CoreAPICompatInspector',
    ],
    'SECURITY_DEFINITIONS': {
        'Token': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
        },
    },
}

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
)

# ADMIN_URL
SITE_ID = env('SITE_ID')

LOGGING_LEVEL = env('LOGGING_LEVEL') if not IS_TEST else 'ERROR'
# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {module} {message}',
            'style': '{',
            'datefmt': '%y %b %d, %H:%M:%S',
        },
        'datadog': {
            'format': '{levelname} Datadog {asctime} {message}',
            'style': '{',
            'datefmt': '%d/%m/%Y %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'datadog': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'datadog',
        },
    },
    'loggers': {
        'celery': {
            'handlers': ['console'],
            'level': LOGGING_LEVEL,
            'propagate': False,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'datadog': {
            'handlers': ['datadog'],
            'level': 'INFO',
            'propagate': False,
        },
        'oauth2_provider': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
        '': {
            'handlers': ['console'],
            'level': LOGGING_LEVEL,
            'propagate': False,
        },
    },
}

# two factor
LOGIN_URL = 'login'
TWO_FACTOR_PATCH_ADMIN = False
LOGIN_REDIRECT_URL = env('LOGIN_REDIRECT_URL')

# ESMS SERVICE
SMS_API_KEY = env('SMS_API_KEY')
SMS_SECRET_KEY = env('SMS_SECRET_KEY')
SMS_OPT_TIMEOUT = env('SMS_OPT_TIMEOUT')
HASH_CODE_AUTO_FILL_SMS = env('HASH_CODE_AUTO_FILL_SMS')

# PUSHER
PUSHER_APP_ID = env('PUSHER_APP_ID')
PUSHER_APP_KEY = env('PUSHER_APP_KEY')
PUSHER_APP_SECRET = env('PUSHER_APP_SECRET')
PUSHER_APP_CLUSTER = env('PUSHER_APP_CLUSTER')

# DISCORD - Thông báo lỗi máy in
DISCORD_WEBHOOK_URL = env('DISCORD_WEBHOOK_URL', default='')
DISCORD_MENTION_ROLE = env('DISCORD_MENTION_ROLE', default='')

# AI XÓA PHÔNG NỀN (Photoroom → remove.bg → rembg local)
PHOTOROOM_API_KEY = env('PHOTOROOM_API_KEY', default='')
REMOVEBG_API_KEY = env('REMOVEBG_API_KEY', default='')

# ONE SIGNAL
ONESIGNAL_APP_KEY = env('ONESIGNAL_APP_KEY')
ONESIGNAL_APP_ID = env('ONESIGNAL_APP_ID')

PHONE_VERIFICATION_TIMEOUT = env('PHONE_VERIFICATION_TIMEOUT')

LANGUAGES = [
    ('vi', _('Vietnamese')),
    ('en', _('English')),
]
LOCALE_PATHS = (
    os.path.join(BASE_DIR, "locale"),
)

DEBUG_HEADER = env('DEBUG_HEADER')

# accounts
ENABLED_FEATURES = {
    'smart_parking',
}

# deploy info
VERSION = env('VERSION')
ENVIRONMENT = env('ENVIRONMENT')
PROJECT_SLUG = env('PROJECT_SLUG')
DOCKER_IMAGE = env('DOCKER_IMAGE')
PRIMARY_SITE_URL = env('PRIMARY_SITE_URL')
SENDBIRD_API_URL = env('SENDBIRD_API_URL')
API_TOKEN_SENDBIRD = env('API_TOKEN_SENDBIRD')

EMAIL_HOST = env('EMAIL_HOST')
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
EMAIL_PORT = env('EMAIL_PORT')
EMAIL_USE_TLS = env('EMAIL_USE_TLS')
AWS_QUERYSTRING_AUTH = False