# Generated by Django 4.2.3 on 2023-08-28 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0003_statusartwork_sizeartwork_prizeartwork_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.colorartwork'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.materialartwork'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='medium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.mediumartwork'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='orientation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.orientationartwork'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='prize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.prizeartwork'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.sizeartwork'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artwork.statusartwork'),
        ),
    ]
