# Generated by Django 4.2.3 on 2023-08-29 03:04

import common.abstract_models.image_field
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0004_artwork_color_artwork_material_artwork_medium_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='image',
        ),
        migrations.CreateModel(
            name='ImageArtwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', common.abstract_models.image_field.CustomImageField(upload_to='')),
                ('artwork', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artwork.artwork')),
            ],
        ),
    ]
