# Generated by Django 4.2.3 on 2023-08-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0005_remove_artwork_image_imageartwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
