# Generated by Django 4.2.3 on 2023-08-29 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0006_alter_artwork_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='creation_date',
        ),
    ]
