# Generated by Django 4.2.3 on 2023-08-31 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0007_remove_artwork_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
