# Generated by Django 4.2.3 on 2023-09-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0009_remove_sizeartwork_name_sizeartwork_depth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='status',
            field=models.CharField(blank=True, choices=[('', '----'), ('sold', 'Sold'), ('available', 'Available for sale'), ('not_for_sale', 'Not for sale'), ('exhibition', 'Exhibition'), ('lost', 'Lost'), ('consignment', 'Consignment'), ('donated_gifted', 'Donated/Gifted'), ('rented', 'Rented'), ('under_maintenance', 'Under Maintenance')], default='', max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='StatusArtwork',
        ),
    ]
