# Generated by Django 4.2.3 on 2023-09-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0010_alter_artwork_status_delete_statusartwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
