# Generated by Django 4.2.3 on 2023-09-14 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0011_alter_artwork_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='prize',
        ),
        migrations.AddField(
            model_name='artwork',
            name='currency',
            field=models.CharField(blank=True, choices=[('vnd', 'VND'), ('usd', 'USD')], default='vnd', max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='PrizeArtwork',
        ),
    ]
