# Generated by Django 4.2.3 on 2023-09-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0012_remove_artwork_prize_artwork_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='is_price_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='currency',
            field=models.CharField(blank=True, choices=[('vnd', 'VND'), ('usd', 'USD')], default='vnd', max_length=5, null=True),
        ),
    ]
