# Generated by Django 4.2.3 on 2023-09-21 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0013_artwork_is_price_visible_artwork_is_public_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='material',
        ),
        migrations.DeleteModel(
            name='MaterialArtwork',
        ),
    ]
