# Generated by Django 4.2.3 on 2023-09-22 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0014_remove_artwork_material_delete_materialartwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
