# Generated by Django 4.2.3 on 2023-09-25 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0016_artwork_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
