# Generated by Django 4.2.3 on 2023-09-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0017_artwork_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='period_created',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='year_created',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
