# Generated by Django 4.2.3 on 2023-09-25 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0018_artwork_period_created_artwork_year_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='edition_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
