# Generated by Django 4.2.3 on 2023-09-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0019_artwork_edition_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='status',
            field=models.CharField(blank=True, choices=[('', '----'), ('sold', 'Sold'), ('available', 'Available for sale'), ('not_for_sale', 'Not for sale'), ('lost', 'Lost'), ('consignment', 'Consignment'), ('donated_gifted', 'Donated/Gifted'), ('under_maintenance', 'Under Maintenance')], default='', max_length=255, null=True),
        ),
    ]
