# Generated by Django 4.2.3 on 2023-10-02 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0020_alter_artwork_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='category',
            field=models.CharField(choices=[('painting', 'Painting'), ('sculpture', 'Sculpture')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='colorartwork',
            name='category',
            field=models.CharField(choices=[('painting', 'Painting'), ('sculpture', 'Sculpture')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mediumartwork',
            name='category',
            field=models.CharField(choices=[('painting', 'Painting'), ('sculpture', 'Sculpture')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orientationartwork',
            name='category',
            field=models.CharField(choices=[('painting', 'Painting'), ('sculpture', 'Sculpture')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sizeartwork',
            name='category',
            field=models.CharField(choices=[('painting', 'Painting'), ('sculpture', 'Sculpture')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='styleartwork',
            name='category',
            field=models.CharField(choices=[('painting', 'Painting'), ('sculpture', 'Sculpture')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subjectartwork',
            name='category',
            field=models.CharField(choices=[('painting', 'Painting'), ('sculpture', 'Sculpture')], max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='CategoryArtwork',
        ),
    ]
