# Generated by Django 4.2.3 on 2023-10-02 04:39

from django.db import migrations

from artwork.utils.migrations.migrate_update_category_artwork import update_category_artwork


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0021_alter_artwork_category_alter_colorartwork_category_and_more'),
    ]

    def migrate_update_category_artwork(apps, schema_editor):
        ArtWork = apps.get_model('artwork', 'ArtWork')
        ColorArtwork = apps.get_model('artwork', 'ColorArtwork')
        MediumArtwork = apps.get_model('artwork', 'MediumArtwork')
        OrientationArtwork = apps.get_model('artwork', 'OrientationArtwork')
        SizeArtwork = apps.get_model('artwork', 'SizeArtwork')
        StyleArtwork = apps.get_model('artwork', 'StyleArtwork')
        SubjectArtwork = apps.get_model('artwork', 'SubjectArtwork')
        update_category_artwork(ArtWork, ColorArtwork, MediumArtwork, OrientationArtwork, SizeArtwork, StyleArtwork,
                                SubjectArtwork)

    operations = [
        migrations.RunPython(migrate_update_category_artwork,
                             migrations.RunPython.noop)
    ]
