# Generated by Django 4.2.3 on 2023-10-03 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userlocation'),
        ('artwork', '0022_auto_20231002_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userlocation'),
        ),
    ]
