# Generated by Django 4.2.3 on 2023-11-13 07:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0023_artwork_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year_of_birth', models.IntegerField()),
                ('id_card', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('contract_number', models.CharField(max_length=50)),
                ('certificate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='artwork.artworkcertificate')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateShipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='artwork.artworkcertificate')),
            ],
        ),
        migrations.CreateModel(
            name='ArtworkEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='artwork.artwork')),
            ],
        ),
        migrations.AddField(
            model_name='artworkcertificate',
            name='artwork_edition',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate', to='artwork.artworkedition'),
        ),
    ]
