# Generated by Django 4.2.3 on 2023-11-14 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0024_artworkcertificate_ownercertificate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='edition_number',
            new_name='total_edition',
        ),
    ]
