# Generated by Django 4.2.3 on 2023-11-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0025_rename_edition_number_artwork_total_edition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownercertificate',
            name='contract_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
