# Generated by Django 4.2.3 on 2023-11-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0026_alter_ownercertificate_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownercertificate',
            name='contract_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
