# Generated by Django 4.2.3 on 2023-11-21 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0027_alter_ownercertificate_contract_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='piece',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
