# Generated by Django 4.2.3 on 2023-12-01 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0028_artwork_piece'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizeartwork',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
