# Generated by Django 4.2.3 on 2023-12-06 04:25

from django.db import migrations

from artwork.utils.migrations.migrate_create_editions_artwork import create_editions_artwork


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0029_sizeartwork_height'),
    ]

    def create_editions_artwork(apps, schema_editor):
        ArtWork = apps.get_model('artwork', 'ArtWork')
        ArtworkEdition = apps.get_model('artwork', 'ArtworkEdition')

        create_editions_artwork(ArtWork, ArtworkEdition)

    operations = [
        migrations.RunPython(create_editions_artwork,
                             migrations.RunPython.noop)
    ]
