# Generated by Django 4.2.3 on 2023-12-08 04:13

from django.db import migrations

from artwork.utils.migrations.migrate_remove_editions_artwork import remove_editions_artwork
from artwork.utils.migrations.migrate_remove_editions_artwork import update_artwork_total_edition


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0030_auto_20231206_0425'),
    ]

    def migrate_remove_editions_artwork(apps, schema_editor):
        ArtworkEdition = apps.get_model('artwork', 'ArtworkEdition')
        remove_editions_artwork(ArtworkEdition)

    def migrate_update_artwork_total_edition(apps, schema_editor):
        Artwork = apps.get_model('artwork', 'ArtWork')
        update_artwork_total_edition(Artwork)

    operations = [
        migrations.RunPython(migrate_remove_editions_artwork, migrations.RunPython.noop),
        migrations.RunPython(migrate_update_artwork_total_edition, migrations.RunPython.noop)
    ]
