# Generated by Django 4.2.3 on 2023-12-10 13:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0031_auto_20231208_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='status',
            field=models.CharField(blank=True, choices=[('', '----'), ('available', 'Available for sale'), ('sold', 'Sold'), ('not_for_sale', 'Not for sale'), ('lost', 'Lost'), ('consignment', 'Consignment'), ('donated_gifted', 'Donated/Gifted'), ('under_maintenance', 'Under Maintenance')], default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='total_edition',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
