# Generated by Django 4.2.3 on 2023-12-13 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0032_alter_artwork_status_alter_artwork_total_edition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateshipping',
            name='certificate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_shipping', to='artwork.artworkcertificate'),
        ),
    ]
