# Generated by Django 4.2.3 on 2023-12-13 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_userprofile_signature'),
        ('artwork', '0033_alter_certificateshipping_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkedition',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userlocation'),
        ),
        migrations.AddField(
            model_name='artworkedition',
            name='status',
            field=models.CharField(blank=True, choices=[('', '----'), ('available', 'Available for sale'), ('sold', 'Sold'), ('not_for_sale', 'Not for sale'), ('lost', 'Lost'), ('consignment', 'Consignment'), ('donated_gifted', 'Donated/Gifted'), ('under_maintenance', 'Under Maintenance')], default='', max_length=255, null=True),
        ),
    ]
