# Generated by Django 4.2.3 on 2023-12-13 10:04

from django.db import migrations

from artwork.utils.migrations.migrate_update_status_and_location_editions_artwork import \
    update_status_and_location_editions_artwork


class Migration(migrations.Migration):
    dependencies = [
        ('artwork', '0034_artworkedition_location_artworkedition_status'),
    ]

    def migrate_update_status_and_location_editions_artwork(apps, schema_editor):
        ArtworkEdition = apps.get_model('artwork', 'ArtworkEdition')
        update_status_and_location_editions_artwork(ArtworkEdition)

    operations = [
        migrations.RunPython(migrate_update_status_and_location_editions_artwork,
                             migrations.RunPython.noop)
    ]
