# Generated by Django 4.2.3 on 2023-12-27 08:28

import common.abstract_models.image_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0035_auto_20231213_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkcertificate',
            name='signature',
            field=common.abstract_models.image_field.CustomImageField(blank=True, null=True, upload_to=''),
        ),
    ]
