# Generated by Django 4.2.3 on 2023-12-28 07:44

from django.db import migrations

from artwork.utils.migrations.migrate_update_signature_artwork_certificate import update_signature_artwork_certificate


class Migration(migrations.Migration):
    dependencies = [
        ('artwork', '0036_artworkcertificate_signature'),
    ]

    def migrate_update_signature_artwork_certificate(apps, schema_editor):
        ArtworkCertificate = apps.get_model('artwork', 'ArtworkCertificate')
        UserProfile = apps.get_model('accounts', 'UserProfile')
        update_signature_artwork_certificate(ArtworkCertificate, UserProfile)

    operations = [
        migrations.RunPython(migrate_update_signature_artwork_certificate,
                             migrations.RunPython.noop)
    ]
