# Generated by Django 4.2.3 on 2024-01-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0037_auto_20231228_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkcertificate',
            name='status',
            field=models.CharField(blank=True, choices=[('', '----'), ('processing', 'Processing'), ('printed', 'Printed'), ('in_transit', 'In transit'), ('delivered', 'Delivered')], default='', max_length=255, null=True),
        ),
    ]
