# Generated by Django 4.2.3 on 2024-01-04 08:19

from django.db import migrations

from artwork.utils.migrations.migrate_update_owner_field_artwork import update_owner_field_artwork


class Migration(migrations.Migration):
    dependencies = [
        ('artwork', '0039_artwork_owner_alter_artwork_artist'),
    ]

    def migrate_update_owner_field_artwork(apps, schema_editor):
        ArtWork = apps.get_model('artwork', 'ArtWork')
        update_owner_field_artwork(ArtWork)

    operations = [
        migrations.RunPython(migrate_update_owner_field_artwork,
                             migrations.RunPython.noop)
    ]
