# Generated by Django 4.2.3 on 2024-01-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0040_auto_20240104_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='artist_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
