# Generated by Django 4.2.3 on 2024-01-09 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artwork', '0041_artwork_artist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkcertificate',
            name='issued_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issued_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artworkcertificate',
            name='issued_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_certificates', to=settings.AUTH_USER_MODEL),
        ),
    ]
