# Generated by Django 4.2.3 on 2024-01-09 09:20

from django.db import migrations

from artwork.utils.migrations.migrate_update_field_issued_by_certificate import update_field_issued_by


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0042_artworkcertificate_issued_by_and_more'),
    ]

    def migrate_update_field_issued_by(apps, schema_editor):
        ArtworkCertificate = apps.get_model('artwork', 'ArtworkCertificate')
        update_field_issued_by(ArtworkCertificate)

    operations = [
        migrations.RunPython(migrate_update_field_issued_by,
                             migrations.RunPython.noop)
    ]
