# Generated by Django 4.2.3 on 2024-01-12 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artwork', '0043_auto_20240109_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Request received'), (2, 'Request approved'), (3, 'Request denied')], default=1, max_length=255, null=True)),
                ('owner_info', models.JSONField(blank=True, null=True)),
                ('shipping_info', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artwork_edition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_requests', to='artwork.artworkedition')),
                ('request_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_requests_made', to=settings.AUTH_USER_MODEL)),
                ('request_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
