# Generated by Django 4.2.3 on 2024-01-17 03:15

import common.abstract_models.image_field
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0044_certificaterequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCertificateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', common.abstract_models.image_field.CustomImageField(upload_to='')),
                ('certificate_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artwork.certificaterequest')),
            ],
        ),
    ]
