# Generated by Django 4.2.3 on 2024-01-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0045_imagecertificaterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequest',
            name='message',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
