# Generated by Django 4.2.3 on 2024-01-24 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0046_certificaterequest_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['id', 'active'], name='artwork_art_id_77c301_idx'),
        ),
    ]
