# Generated by Django 4.2.3 on 2024-01-29 03:34

from django.db import migrations

from artwork.utils.migrations.migrate_update_field_status import update_field_status


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0047_artwork_active_artwork_artwork_art_id_77c301_idx'),
    ]

    def migrate_update_field_status_artwork(apps, schema_editor):
        Artwork = apps.get_model('artwork', 'ArtWork')
        update_field_status(Artwork)

    operations = [
        migrations.RunPython(migrate_update_field_status_artwork,
                             migrations.RunPython.noop)
    ]
