# Generated by Django 4.2.3 on 2024-02-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0048_auto_20240129_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediumartwork',
            name='name_vi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orientationartwork',
            name='name_vi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='styleartwork',
            name='name_vi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subjectartwork',
            name='name_vi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
