# Generated by Django 4.2.3 on 2024-02-20 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artwork', '0049_mediumartwork_name_vi_orientationartwork_name_vi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediumartwork',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mediums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='styleartwork',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='styles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subjectartwork',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to=settings.AUTH_USER_MODEL),
        ),
    ]
