# Generated by Django 4.2.3 on 2024-02-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0050_mediumartwork_user_styleartwork_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkcertificate',
            name='status',
            field=models.CharField(blank=True, choices=[('', '----'), ('information_received', 'Information received'), ('certificate_exported', 'Certificate exported'), ('shipping_unit_received', 'Shipping unit received'), ('completed', 'Completed')], default='', max_length=255, null=True),
        ),
    ]
