# Generated by Django 4.2.3 on 2024-02-23 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0051_alter_artworkcertificate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='description',
            field=models.CharField(blank=True, max_length=6000),
        ),
    ]
