# Generated by Django 4.2.3 on 2024-03-21 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0053_ownercertificate_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownercertificate',
            old_name='owner',
            new_name='user',
        ),
    ]
