# Generated by Django 4.2.3 on 2024-03-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0054_rename_owner_ownercertificate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediumartwork',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='mediumartwork',
            name='name_vi',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='styleartwork',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='styleartwork',
            name='name_vi',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='subjectartwork',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='subjectartwork',
            name='name_vi',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
