# Generated by Django 4.2.3 on 2024-04-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0055_alter_mediumartwork_name_alter_mediumartwork_name_vi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediumartwork',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mediumartwork',
            name='name_vi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orientationartwork',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orientationartwork',
            name='name_vi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='styleartwork',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='styleartwork',
            name='name_vi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subjectartwork',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subjectartwork',
            name='name_vi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
