# Generated by Django 4.2.3 on 2024-04-08 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0056_alter_mediumartwork_name_alter_mediumartwork_name_vi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='linked_artwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_artworks', to='artwork.artwork'),
        ),
        migrations.AddField(
            model_name='artworkedition',
            name='linked_edition',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_edition_related', to='artwork.artworkedition'),
        ),
    ]
