# Generated by Django 4.2.3 on 2024-05-03 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0057_artwork_linked_artwork_artworkedition_linked_edition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownercertificate',
            name='id_card',
        ),
    ]
