# Generated by Django 4.2.3 on 2024-05-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0058_remove_ownercertificate_id_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='is_public_certificate',
            field=models.BooleanField(default=True),
        ),
    ]
