# Generated by Django 4.2.3 on 2024-05-09 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0059_alter_artwork_artist'),
        ('artwork', '0059_artwork_is_public_certificate'),
    ]

    operations = [
    ]
