# Generated by Django 4.2.3 on 2024-05-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0060_merge_20240509_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
