# Generated by Django 4.2.3 on 2024-05-30 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0061_artwork_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='is_ask_price_visible',
            field=models.BooleanField(default=False),
        ),
    ]
