# Generated by Django 4.2.3 on 2024-05-30 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0062_artwork_is_ask_price_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='contact_information',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
