# Generated by Django 4.2.3 on 2024-06-12 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0063_artwork_contact_information'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='artworkedition',
            unique_together={('artwork', 'edition_number')},
        ),
    ]
