# Generated by Django 4.2.3 on 2024-06-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0064_alter_artworkedition_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='is_price_visible',
        ),
        migrations.AddField(
            model_name='artwork',
            name='is_hide_price',
            field=models.BooleanField(default=False),
        ),
    ]
