# Generated by Django 4.2.3 on 2024-06-20 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artwork', '0065_remove_artwork_is_price_visible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistTagRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Request received'), (2, 'Request approved'), (3, 'Request denied')], default=1, null=True)),
                ('message', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artwork', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tag_request', to='artwork.artwork')),
                ('request_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_tag_requests_made', to=settings.AUTH_USER_MODEL)),
                ('request_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_tag_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
