# Generated by Django 4.2.3 on 2024-07-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0066_artisttagrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='contact_info_artist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
