# Generated by Django 4.2.3 on 2024-07-12 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0067_artwork_contact_info_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='cost_price',
        ),
    ]
