# Generated by Django 4.2.3 on 2024-07-15 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0068_remove_artwork_cost_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisttagrequest',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_request', to='artwork.artwork'),
        ),
    ]
