# Generated by Django 4.2.3 on 2024-07-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0069_alter_artisttagrequest_artwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisttagrequest',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Request received'), (2, 'Request approved'), (3, 'Request denied'), (4, 'Request canceled')], default=1, null=True),
        ),
    ]
