# Generated by Django 4.2.3 on 2024-09-09 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artwork', '0071_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_collections', to='artwork.collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'collection')},
            },
        ),
    ]
