# Generated by Django 4.2.3 on 2024-11-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0073_likeartwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='artworks', to='artwork.subjectartwork'),
        ),
    ]
