# Generated by Django 4.2.3 on 2024-11-04 08:41

from django.db import migrations

from artwork.utils.migrations.migrate_subject_to_subjects import update_subject_to_subjects


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0074_artwork_subjects'),
    ]

    def migrate_subject_to_subjects(apps, schema_editor):
        Artwork = apps.get_model('artwork', 'ArtWork')
        update_subject_to_subjects(Artwork)

    operations = [
        migrations.RunPython(migrate_subject_to_subjects,
                             migrations.RunPython.noop)
    ]
