# Generated by Django 4.2.3 on 2024-11-19 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0075_auto_20241104_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='year_of_birth_artist',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
