# Generated by Django 4.2.3 on 2024-11-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0076_artwork_year_of_birth_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='year_of_birth_artist',
            field=models.CharField(blank=True, null=True),
        ),
    ]
