# Generated by Django 4.2.3 on 2024-11-20 07:32

from django.db import migrations

from artwork.utils.migrations.migrate_update_uuid_collection import update_field_uuid_collection


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0078_collection_uuid'),
    ]

    def migrate_update_field_uuid_collection(apps, schema_editor):
        Collection = apps.get_model('artwork', 'Collection')
        update_field_uuid_collection(Collection)

    operations = [
        migrations.RunPython(migrate_update_field_uuid_collection,
                             migrations.RunPython.noop)
    ]
