# Generated by Django 4.2.3 on 2024-11-29 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artwork', '0080_alter_collection_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=100, null=True)),
                ('year_of_birth', models.CharField(blank=True, max_length=4, null=True)),
                ('create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('artist_name', 'year_of_birth', 'create_user')},
            },
        ),
        migrations.AddField(
            model_name='artwork',
            name='artist_artwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artworks', to='artwork.artworkartist'),
        ),
    ]
