# Generated by Django 4.2.3 on 2024-11-29 08:28

from django.db import migrations

from artwork.utils.migrations.migrate_move_data_to_artwork_artist import move_data_to_artwork_artist


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0081_artworkartist_artwork_artist_artwork'),
    ]

    def migrate_move_data_to_artwork_artist(apps, schema_editor):
        Artwork = apps.get_model('artwork', 'ArtWork')
        ArtworkArtist = apps.get_model('artwork', 'ArtworkArtist')
        move_data_to_artwork_artist(Artwork, ArtworkArtist)

    operations = [
        migrations.RunPython(migrate_move_data_to_artwork_artist,
                             migrations.RunPython.noop)
    ]
