# Generated by Django 4.2.17 on 2024-12-12 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0082_auto_20241129_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='is_public_certificate',
            field=models.BooleanField(default=False),
        ),
    ]
