# Generated by Django 4.2.3 on 2024-12-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0082_auto_20241129_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkartist',
            name='year_of_death',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
