# Generated by Django 4.2.17 on 2024-12-12 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0083_alter_artwork_is_public_certificate'),
        ('artwork', '0083_artworkartist_year_of_death'),
    ]

    operations = [
    ]
