# Generated by Django 4.2.17 on 2024-12-31 09:35

import common.abstract_models.image_field
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artwork', '0084_merge_20241212_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('address', models.TextField(blank=True)),
                ('event_type', models.CharField(blank=True, choices=[('free', 'Free Ticket'), ('sale', 'Ticket Sale'), ('private', 'Private Event')], max_length=10, null=True)),
                ('cover_image', common.abstract_models.image_field.CustomImageField(blank=True, null=True, upload_to='')),
                ('preface', models.TextField(blank=True, max_length=6000)),
                ('organizer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('organizer_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organized_exhibitions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExhibitionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('artworks', models.ManyToManyField(related_name='exhibition_groups', to='artwork.artwork')),
                ('exhibition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='artwork.exhibition')),
            ],
        ),
    ]
