# Generated by Django 4.2.17 on 2024-12-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0084_merge_20241212_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='description',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='note',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
