# Generated by Django 4.2.17 on 2024-12-31 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artwork', '0085_exhibition_exhibitiongroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='organizer_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exhibitions', to=settings.AUTH_USER_MODEL),
        ),
    ]
