# Generated by Django 4.2.17 on 2025-01-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0086_alter_exhibition_organizer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='event_type',
            field=models.CharField(blank=True, choices=[('free_ticket', 'Free Ticket'), ('ticket_sale', 'Ticket Sale'), ('private_event', 'Private Event')], max_length=50, null=True),
        ),
    ]
