# Generated by Django 4.2.17 on 2025-01-02 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0085_alter_artwork_description_alter_artwork_note'),
        ('artwork', '0086_alter_exhibition_organizer_user'),
    ]

    operations = [
    ]
