# Generated by Django 4.2.17 on 2025-01-03 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0087_alter_exhibition_event_type'),
        ('artwork', '0087_merge_20250102_0805'),
    ]

    operations = [
    ]
