# Generated by Django 4.2.17 on 2025-01-08 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artwork', '0088_merge_20250103_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exhibitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='organizer_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organized_exhibitions', to=settings.AUTH_USER_MODEL),
        ),
    ]
