# Generated by Django 4.2.17 on 2025-01-08 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0089_exhibition_is_draft_exhibition_is_public_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibition',
            name='organizer_user',
        ),
    ]
