# Generated by Django 4.2.17 on 2025-03-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0090_remove_exhibition_organizer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='curator',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
