# Generated by Django 4.2.17 on 2025-05-14 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0091_exhibition_curator'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='inventory_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
