# Generated by Django 4.2.17 on 2025-05-20 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0092_artwork_inventory_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='total_edition',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='ownercertificate',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ownercertificate',
            name='year_of_birth',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
