# Generated by Django 4.2.3 on 2024-11-29 08:28

from django.db import migrations

from artwork.utils.migrations.migrate_update_artwork_is_public import update_artwork_is_public_to_true


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0093_alter_artwork_total_edition_and_more'),
    ]

    def migrate_update_artwork_is_public(apps, schema_editor):
        ArtWork = apps.get_model('artwork', 'ArtWork')
        Collection = apps.get_model('artwork', 'Collection')
        Exhibition = apps.get_model('artwork', 'Exhibition')
        update_artwork_is_public_to_true(ArtWork, Collection, Exhibition)

    operations = [
        migrations.RunPython(migrate_update_artwork_is_public,
                             migrations.RunPython.noop)
    ]