# Generated by Django 4.2.17 on 2025-09-26 08:02

import common.abstract_models.image_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0094_auto_20250804_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='audio_file',
            field=common.abstract_models.image_field.CustomFileField(blank=True, null=True, upload_to=''),
        ),
    ]
