# Generated by Django 4.2.17 on 2025-10-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0096_commentartwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentartwork',
            name='is_hidden',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
