# Generated by Django 4.2.17 on 2025-11-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0097_commentartwork_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='in_stock_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='status',
            field=models.CharField(blank=True, choices=[('', '----'), ('available', 'Available for sale'), ('sold', 'Sold'), ('not_for_sale', 'Not for sale'), ('lost', 'Lost'), ('consignment', 'Consignment'), ('donated_gifted', 'Donated/Gifted'), ('under_maintenance', 'Under Maintenance'), ('in_stock', 'In Stock')], default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artworkedition',
            name='status',
            field=models.CharField(blank=True, choices=[('', '----'), ('available', 'Available for sale'), ('sold', 'Sold'), ('not_for_sale', 'Not for sale'), ('lost', 'Lost'), ('consignment', 'Consignment'), ('donated_gifted', 'Donated/Gifted'), ('under_maintenance', 'Under Maintenance'), ('in_stock', 'In Stock')], default='', max_length=255, null=True),
        ),
    ]
