# Generated by Django on 2025-12-03

from django.db import migrations

from artwork.utils.migrations.migrate_artist_tag_to_artist import migrate_artist_tag_to_artist


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0098_artwork_in_stock_date_alter_artwork_status_and_more'),
    ]

    def run_migration(apps, schema_editor):
        ArtWork = apps.get_model('artwork', 'ArtWork')
        migrate_artist_tag_to_artist(ArtWork)

    operations = [
        migrations.RunPython(run_migration, migrations.RunPython.noop)
    ]
