# Generated by Django 4.2.17 on 2025-12-03 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artwork', '0099_conditionimagebatch_conditionimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionImageBatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images_snapshot', models.JSONField(default=list)),
                ('update_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condition_image_logs', to=settings.AUTH_USER_MODEL)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_image_logs', to='artwork.artwork')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='artwork.conditionimagebatch')),
            ],
            options={
                'ordering': ('created_at', 'id'),
                'indexes': [models.Index(fields=['artwork', 'created_at'], name='artwork_con_artwork_6560cc_idx'), models.Index(fields=['batch', 'created_at'], name='artwork_con_batch_i_1096f3_idx')],
            },
        ),
    ]
