# Generated by Django 4.2.17 on 2025-12-17 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0099_migrate_artist_tag_to_artist'),
        ('artwork', '0100_conditionimagebatchlog'),
    ]

    operations = [
    ]
