# Generated by Django 4.2.17 on 2025-12-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0100_conditionimagebatchlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkedition',
            name='currency',
            field=models.CharField(blank=True, choices=[('vnd', 'VND'), ('usd', 'USD')], default='vnd', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='artworkedition',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artworkedition',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
