# Generated by Django 4.2.17 on 2025-12-18 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0101_artworkedition_currency_artworkedition_owner_name_and_more'),
        ('artwork', '0101_merge_20251217_0427'),
    ]

    operations = [
    ]
