# Generated by Django 4.2.17 on 2025-12-22 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0102_merge_20251218_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='show_comments',
            field=models.BooleanField(default=False),
        ),
    ]
