# Generated by Django 4.2.17 on 2025-12-29 03:18

from django.db import migrations
from artwork.utils.migrations.migrate_backfill_certificate_for_artist_editions import (
    backfill_certificate_for_artist_editions,
)


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0103_artwork_show_comments'),
    ]

    def migrate_backfill_certificate_for_artist_editions(apps, schema_editor):
        ArtWork = apps.get_model('artwork', 'ArtWork')
        ArtworkEdition = apps.get_model('artwork', 'ArtworkEdition')
        ArtworkCertificate = apps.get_model('artwork', 'ArtworkCertificate')
        OwnerCertificate = apps.get_model('artwork', 'OwnerCertificate')

        backfill_certificate_for_artist_editions(
            ArtWork,
            ArtworkEdition,
            ArtworkCertificate,
            OwnerCertificate,
        )

    operations = [
        migrations.RunPython(migrate_backfill_certificate_for_artist_editions, migrations.RunPython.noop),
    ]
