# Generated by Django 4.2.17 on 2026-01-12 04:24

import common.abstract_models.image_field
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artwork', '0104_auto_20251229_0318'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('banner', common.abstract_models.image_field.CustomImageField(blank=True, null=True, upload_to='')),
                ('share_type', models.CharField(choices=[('artwork', 'Artwork'), ('exhibition', 'Exhibition'), ('mixed', 'Mixed')], default='artwork', max_length=20)),
                ('recipient_type', models.CharField(choices=[('public', 'Public Link'), ('specific', 'Specific Users'), ('both', 'Both')], default='public', max_length=20)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('expiration_type', models.CharField(choices=[('never', 'Never'), ('custom', 'Custom')], default='never', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_count', models.IntegerField(default=0)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('shared_items', models.JSONField(default=list)),
                ('recipients', models.ManyToManyField(blank=True, related_name='received_share_links', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
