# Generated by Django 4.2.17 on 2026-01-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0105_sharelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharelink',
            name='is_share_all',
            field=models.BooleanField(default=False),
        ),
    ]
