# Generated by Django 4.2.17 on 2026-01-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0106_sharelink_is_share_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharelink',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='collection_share_links', to='artwork.collection'),
        ),
    ]
