# Generated by Django 4.2.17 on 2026-01-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0107_sharelink_collections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharelink',
            name='share_type',
            field=models.CharField(choices=[('artwork', 'Artwork'), ('collection', 'Collection'), ('exhibition', 'Exhibition'), ('mixed', 'Mixed')], default='artwork', max_length=20),
        ),
    ]
