# Generated by Django 4.2.17 on 2026-02-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0108_alter_sharelink_share_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharelink',
            name='artwork',
            field=models.ManyToManyField(blank=True, related_name='share_links', to='artwork.artwork'),
        ),
    ]
