# Generated by Django 4.2.17 on 2026-02-02 03:34

from django.db import migrations
from artwork.utils.migrations.migrate_share_link_artwork import migrate_shared_items_to_artwork_field


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0109_sharelink_artwork'),
    ]

    def forward(apps, schema_editor):
        ShareLink = apps.get_model('artwork', 'ShareLink')
        ArtWork = apps.get_model('artwork', 'ArtWork')
        migrate_shared_items_to_artwork_field(ShareLink, ArtWork)

    operations = [
        migrations.RunPython(forward,
                             migrations.RunPython.noop)
    ]
