# Generated by Django 4.2.17 on 2026-02-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0110_auto_20260202_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='uuid',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
