# Generated by Django 4.2.17 on 2026-02-02 07:53

from django.db import migrations

from artwork.utils.migrations.migrate_backfill_artwork_uuid import backfill_artwork_uuid


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0111_artwork_uuid'),
    ]

    def migrate_backfill_artwork_uuid(apps, schema_editor):
        ArtWork = apps.get_model('artwork', 'ArtWork')
        backfill_artwork_uuid(ArtWork)

    operations = [
        migrations.RunPython(migrate_backfill_artwork_uuid, migrations.RunPython.noop),
    ]
