# Generated by Django 4.2.17 on 2026-02-02 07:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0112_auto_20260202_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
