# Generated by Django 4.2.17 on 2026-02-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0113_alter_artwork_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='is_certificate_sync_disabled',
            field=models.BooleanField(default=False, help_text='When True, certificates will not be synced when artwork is updated. This is set permanently once any certificate of the artwork has been transferred.'),
        ),
    ]
