# Generated by Django 4.2.17 on 2026-02-25 06:58

from django.db import migrations

from artwork.utils.migrations.migrate_backfill_certificates_for_artist_artworks import (
    backfill_certificates_for_artist_artworks,
)


def run_backfill(apps, schema_editor):
    ArtWork = apps.get_model('artwork', 'ArtWork')
    ArtworkEdition = apps.get_model('artwork', 'ArtworkEdition')
    ArtworkCertificate = apps.get_model('artwork', 'ArtworkCertificate')
    OwnerCertificate = apps.get_model('artwork', 'OwnerCertificate')

    backfill_certificates_for_artist_artworks(
        ArtWork,
        ArtworkEdition,
        ArtworkCertificate,
        OwnerCertificate,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0114_artwork_is_certificate_sync_disabled'),
    ]

    operations = [
        migrations.RunPython(
            run_backfill, migrations.RunPython.noop
        ),
    ]
