# Generated by Django 4.2.17 on 2026-03-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0115_auto_20260225_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='inventory_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
