# Generated by Django 4.2.17 on 2026-03-22 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0117_collector_ownership_transfer'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='collectorownershiptransfer',
            new_name='artwork_col_transfe_f95fb0_idx',
            old_name='artwork_col_trans_idx',
        ),
    ]
