# Generated by Django 4.2.3 on 2024-08-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatelog',
            name='action_type',
            field=models.CharField(choices=[('export', 'Export Certificate'), ('verify', 'Verify Certificate')], default='export'),
        ),
    ]
