# Generated by Django 4.2.17 on 2025-10-24 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artwork', '0095_artwork_audio_file'),
        ('activity_log', '0002_certificatelog_action_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('update_title', 'Update Title'), ('update_description', 'Update Description'), ('update_note', 'Update Note'), ('update_inventory_code', 'Update Inventory Code'), ('update_status', 'Update Status'), ('update_location', 'Update Location'), ('update_year_created', 'Update Year Created'), ('update_period_created', 'Update Period Created'), ('update_price', 'Update Price'), ('update_currency', 'Update Currency'), ('update_is_public_certificate', 'Update Certificate Public Status'), ('update_style', 'Update Style'), ('update_subjects', 'Update Subjects'), ('update_medium', 'Update Medium'), ('update_orientation', 'Update Orientation'), ('update_size', 'Update Size'), ('certificate_issued', 'Certificate Issued'), ('image_added', 'Image Added'), ('image_removed', 'Image Removed'), ('audio_added', 'Audio Added'), ('audio_removed', 'Audio Removed'), ('audio_updated', 'Audio Updated'), ('added_to_exhibition', 'Added to Exhibition'), ('delete_artwork', 'Delete Artwork'), ('updated_details', 'Updated Details'), ('edition_updated', 'Edition Updated')], help_text='Type of action performed', max_length=50)),
                ('field_name', models.CharField(blank=True, help_text='Name of the field that was changed', max_length=50, null=True)),
                ('old_value', models.TextField(blank=True, help_text='Previous value before the change', null=True)),
                ('new_value', models.TextField(blank=True, help_text='New value after the change', null=True)),
                ('description', models.TextField(help_text='Human-readable description of the action')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this action was performed')),
                ('artwork', models.ForeignKey(blank=True, help_text='The artwork this log entry is related to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='artwork.artwork')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artwork_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Artwork Activity Log',
                'verbose_name_plural': 'Artwork Activity Logs',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['artwork', '-created_at'], name='activity_lo_artwork_ae1f94_idx'), models.Index(fields=['-created_at'], name='activity_lo_created_39a930_idx')],
            },
        ),
    ]
