# Generated by Django 4.2.17 on 2025-10-31 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0003_artworklog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artworklog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='artworklog',
            name='field_name',
        ),
        migrations.RemoveField(
            model_name='artworklog',
            name='new_value',
        ),
        migrations.RemoveField(
            model_name='artworklog',
            name='old_value',
        ),
        migrations.AddField(
            model_name='artworklog',
            name='content_en',
            field=models.TextField(default='', help_text='Snapshot English content at the time of logging'),
        ),
        migrations.AddField(
            model_name='artworklog',
            name='content_vi',
            field=models.TextField(default='', help_text='Snapshot Vietnamese content at the time of logging'),
        ),
        migrations.AddField(
            model_name='artworklog',
            name='params',
            field=models.JSONField(blank=True, default=dict, help_text='Arbitrary parameters snapshot (e.g., old/new values, field names)'),
        ),
        migrations.AddField(
            model_name='artworklog',
            name='template_en',
            field=models.TextField(blank=True, help_text='English template at the time of logging', null=True),
        ),
        migrations.AddField(
            model_name='artworklog',
            name='template_vi',
            field=models.TextField(blank=True, help_text='Vietnamese template at the time of logging', null=True),
        ),
        migrations.AlterField(
            model_name='artworklog',
            name='action_type',
            field=models.CharField(choices=[('artwork_updated', 'Artwork Updated'), ('certificate_issued', 'Certificate Issued'), ('certificate_requested', 'Certificate Requested'), ('certificate_reject', 'Certificate Rejected')], help_text='Type of action performed', max_length=50),
        ),
        migrations.AddIndex(
            model_name='artworklog',
            index=models.Index(fields=['action_type'], name='activity_lo_action__934472_idx'),
        ),
    ]
