# Generated by Django 4.2.17 on 2025-10-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0003_artworklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworklog',
            name='action_type',
            field=models.CharField(choices=[('update_title', 'Update Title'), ('update_description', 'Update Description'), ('update_note', 'Update Note'), ('update_inventory_code', 'Update Inventory Code'), ('update_status', 'Update Status'), ('update_location', 'Update Location'), ('update_year_created', 'Update Year Created'), ('update_period_created', 'Update Period Created'), ('update_price', 'Update Price'), ('update_currency', 'Update Currency'), ('update_is_public_certificate', 'Update Certificate Public Status'), ('update_style', 'Update Style'), ('update_subjects', 'Update Subjects'), ('update_medium', 'Update Medium'), ('update_orientation', 'Update Orientation'), ('update_size', 'Update Size'), ('certificate_issued', 'Certificate Issued'), ('certificate_requested', 'Certificate Requested'), ('certificate_reject', 'Certificate Rejected'), ('image_added', 'Image Added'), ('image_removed', 'Image Removed'), ('audio_added', 'Audio Added'), ('audio_removed', 'Audio Removed'), ('audio_updated', 'Audio Updated'), ('added_to_exhibition', 'Added to Exhibition'), ('delete_artwork', 'Delete Artwork'), ('updated_details', 'Updated Details'), ('edition_updated', 'Edition Updated')], help_text='Type of action performed', max_length=50),
        ),
    ]
