# Generated by Django 4.2.17 on 2025-11-02 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0004_alter_artworklog_action_type'),
        ('activity_log', '0004_remove_artworklog_description_and_more'),
    ]

    operations = [
    ]
