# Generated by Django 4.2.17 on 2025-11-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0005_merge_20251102_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworklog',
            name='action_type',
            field=models.CharField(choices=[('artwork_updated', 'Artwork Updated'), ('certificate_issued', 'Certificate Issued'), ('certificate_requested', 'Certificate Requested'), ('certificate_reject', 'Certificate Rejected'), ('artwork_uploaded', 'Artwork Uploaded')], help_text='Type of action performed', max_length=50),
        ),
    ]
