# Generated by Django 4.2.17 on 2025-11-17 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity_log', '0006_alter_artworklog_action_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('user_gladius_id_updated', 'User Gladius ID Updated')], help_text='Type of action performed', max_length=50)),
                ('template_vi', models.TextField(blank=True, help_text='Vietnamese template at the time of logging', null=True)),
                ('template_en', models.TextField(blank=True, help_text='English template at the time of logging', null=True)),
                ('content_vi', models.TextField(default='', help_text='Snapshot Vietnamese content at the time of logging')),
                ('content_en', models.TextField(default='', help_text='Snapshot English content at the time of logging')),
                ('params', models.JSONField(blank=True, default=dict, help_text='Arbitrary parameters snapshot (e.g., old/new values, field names)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this action was performed')),
                ('user', models.ForeignKey(blank=True, help_text='User this log entry is related to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
